Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,6 +46,13 @@ jobs:
             exit 1
           fi
           
+          if [ -f script.js ]; then
+            echo "styles.css file found!"
+          else
+            echo "styles.css file not found!"
+            exit 1
+          fi
+          
           # Ensure to capture the result of the BVT execution
 
           # Example exit code handling for success or failure
